name: goquorum-parser_services

services:
  goquorum-parser-backend:
    image: goquorum-parser-services:latest
    pull_policy: never
    container_name: backend
    environment:
      - SERVICE_NAME=backend
    networks:
      - quorum-network

networks:
  quorum-network:
    name: quorum-network
    external: true