name: goquorum-parser_infrastructure
services:
  ##############################################
  # Transport (NATS)
  ##############################################
  goquorum-parser_nats:
    image: nats:2.10.14-alpine
    container_name: nats
    ports:
      - "4223:4222"
      # localhost:8223 - NATS management
      - "8223:8222"
    command:
      [ "-js", "--http_port", "8222" ]

  ##############################################
  # Databases (Postgres instances)
  ##############################################
  goquorum-parser_database:
    image: postgres:15-alpine
    container_name: database
    ports:
      - "5443:5432"
    volumes: 
      - goquorum-parser-postgres:/var/lib/postgresql/data
      - ./postgresql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=goquorum-parser_user
      - POSTGRES_PASSWORD=goquorum-parser_pass
      - POSTGRES_MULTIPLE_DATABASES=cryptogate_db

volumes:
  goquorum-parser-postgres:
    name: goquorum-parser-postgres
    labels:
      - project=goquorum-parser

networks:
  default:
    name: network