name: goquorum-parser_infrastructure
services:
  ##############################################
  # Transport (NATS)
  ##############################################
  goquorum-parser-nats:
    image: nats:2.10.14-alpine
    container_name: goquorum-parser-nats
    ports:
      - "4223:4222"
      # localhost:8223 - NATS management
      - "8223:8222"
    command:
      [ "-js", "--http_port", "8222" ]
    networks:
      - quorum-dev-quickstart

  ##############################################
  # Databases (Postgres instances)
  ##############################################
  goquorum-parser-database:
    image: postgres:15-alpine
    container_name: goquorum-parser-database
    ports:
      - "5444:5432"
    volumes: 
      - goquorum-parser-postgres:/var/lib/postgresql/data
      - ./postgresql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=goquorum_parser_user
      - POSTGRES_PASSWORD=goquorum_parser_pass
      - POSTGRES_MULTIPLE_DATABASES=backend_db
    networks:
      - quorum-dev-quickstart

volumes:
  goquorum-parser-postgres:
    name: goquorum-parser-postgres
    labels:
      - project=goquorum-parser

networks:
  quorum-dev-quickstart:
    name: quorum-dev-quickstart
    external: true